### ISSUE TITLE
A letter for the code.

### ISSUE THREAD

**Issue by cuitdongxiaofeng** [scilus/scilpy#1]
Dear Sir,
   I am reading your paper on SET.I want to reproduce the process in your paper, but the scilpy toolkit can't be downloaded for the time being. When will it be convenient for you to provide the code about scilpy?
I am looking forward to your reply.

**Comment by StongeEtienne** [comment]
https://github.com/StongeEtienne/trimeshpy/issues/1

**Comment by jchoude** [comment]
Hi @cuitdongxiaofeng you can now see that code is available here. The missing SET parts should be coming in the next few weeks.

**Comment by jchoude** [comment]
Never had any answer, let's drop this.
