### ISSUE TITLE
scil_tractogram_filter_by_length save_rejected option does nothing

### ISSUE THREAD

**Issue by karanphil** [scilus/scilpy#1007]
The `save_rejected` argument in `scil_tractogram_filter_by_length.py` is never used in the script. @frheault , I might have time to do a PR to fix it, but maybe you have a preference on how to use it.

**Comment by frheault** [comment]
I never use these '--save_inverse' or '--save_rejected' in for filtering. I think it was initially needed by @arnaudbore for Extractor with Laurent?

**Comment by levje** [comment]
Should be fixed in the PR #1090
