### ISSUE TITLE
Possible upcoming issue with panda

### ISSUE THREAD

**Issue by EmmaRenauld** [scilus/scilpy#1044]
See this warning:

![image](https://github.com/user-attachments/assets/6a8e723d-789d-4a52-9ff7-5c7c31ba57f3)

Also, panda is used but is not in the requirements per say (but gets installed:

`Requirement already satisfied: pandas>=1.2 in site-packages (from formulaic==0.3.*->scilpy==2.0.2) (2.2.0)`)

**Comment by arnaudbore** [comment]
Closing until we figure out how did we get this warning message :D
