### ISSUE TITLE
scil_viz_fodf.py can't visulize peaks.

### ISSUE THREAD

**Issue by gaunny** [scilus/scilpy#1072]
Hi, I met the problem when I visulized the fODFs and peaks  using scil_viz_fodf.py.  The script I used is " python scil_viz_fodf.py --peaks ismrm2015_peaks.nii.gz ismrm2015_fodf.nii.gz ". However, only the fODFs are showed. The result is shown here: 
![image](https://github.com/user-attachments/assets/bb7b46ce-22a6-4057-a72f-50373a691d4e)

**Comment by arnaudbore** [comment]
Hello @gaunny ,

Peaks can be hidden within the FODF. You can increase the size of them with the option `--peaks_length`
Hope it helps.
Arnaud

**Comment by CHrlS98** [comment]
Hi @gaunny, there seems to be a bug with the script when showing asymmetric peaks. I can't make it work either. I'll investigate and get back to you.
