### ISSUE TITLE
visualize connectivity enhancement

### ISSUE THREAD

**Issue by mdesco** [scilus/scilpy#179]
If possible, it would be nice to merge visu options from @StongeEtienne in the what @frheault wrote. @StongeEtienne visualize connectivity matrix is called npy2png.
https://www.dropbox.com/s/uvgafmkyxo1ud37/npy2png.py?dl=0

Should not be too hard to implement. @StongeEtienne can you do it when you have a bit of time?

Thanks!

**Comment by frheault** [comment]
@mdesco The only options missing are --remove_diag, --symmetrize. Is this a feature you want, if yes I will add them to scil_connectivity_math.py instead (since it is useful outside of visualization)

**Comment by arnaudbore** [comment]
@mdesco , @frheault should we close this PR or not ?
