### ISSUE TITLE
label_list.txt info

### ISSUE THREAD

**Issue by mdesco** [scilus/scilpy#189]
We need an example or a description somewhere of what a label_list looks like for the scil_compute_connectivity.py.

The PRs had very rich info on example data and example scripts calling the functions which are now lost since the PR are merged. It would be amazing to find a way to bring into the doc or elsewhere... 

I had to go back in old PRs to find an example how to call scil_compute_connectivity with examples as inputs.

@frheault any idea how to easy this? Otherwise, your mailbox and slack will explode

**Comment by frheault** [comment]
@arnaudbore can be closed.
