### ISSUE TITLE
scil_compute_connectivity output extension

### ISSUE THREAD

**Issue by mdesco** [scilus/scilpy#190]
Please add to the help the extensions expected for --volume, --streamline_count, etc.....

@frheault

**Comment by mdesco** [comment]
Also, not sure I understand the difference with --maps and --metrics. Reading the --help, looks the same. Looking at PR, I only --maps but no example with --metrics

**Comment by mdesco** [comment]
Also, please change --density_weigthing -> --density_weig**h**ting

thanks

**Comment by frheault** [comment]
@arnaudbore can be closed.
