### ISSUE TITLE
Update scipy for python 3.7

### ISSUE THREAD

**Issue by arnaudbore** [scilus/scilpy#198]
scipy==1.0.1 is not enough for python 3.7
Which version should we use ? 
What needs to be modified ?

**Comment by StongeEtienne** [comment]
scipy==1.2.1 work for the build (python 3.7),
however it would need to be tested with scripts.

Also we have a package installed twice with different name "scikit-learn-0.22.1. AND "sklearn-0.0"
after the "pip install -r requirements.txt "

**Comment by frheault** [comment]
@GuillaumeTh Is this still relevant? Can you check the current state of the master?

**Comment by arnaudbore** [comment]
Working on my laptop with 3.7 and travis seems to like it as well. I close this.
