### ISSUE TITLE
docstring look of scil_filter_connectivity.py

### ISSUE THREAD

**Issue by mdesco** [scilus/scilpy#200]
@frheault can you fix the first paragraph of scil_filter_connectivity docstring please. It is unreadable. I just see 1 big block of text.

Script to facilitate filtering of connectivity matrices. The same could be
achieved through a complex sequence of scil_connectivity_math.py. Can be used
with any connectivity matrix from scil_compute_connectivity.py. For example, a
simple filtering (Jasmeen style) would be: scil_filter_connectivity.py
out_mask.npy --greater_than */sc.npy 1 0.90 --lower_than */sim.npy 2 0.90
--greater_than */len.npy 40 0.90 -v; This will result in a binary mask where
each node with a value of 1 represents a node with at least 90% of the
population having at least 1 streamline, 90% of the population is similar to
the average (2mm) and 90% of the population having at least 40mm of average
streamlines length. --greater_than or --lower_than expect the same convention:
MATRICES_LIST VALUE_THR POPULATION_PERC It is strongly recommended (but not
enforced) that the same number of connectivity matrices is used for each
condition. This script performs an intersection of all conditions, meaning
that all conditions must be met in order not to be filtered. If the user wants
to manually handle the requirements, --keep_condition_count can be used and
manually binarized using scil_connectivity_math.py

thanks

**Comment by frheault** [comment]
My mistake, I used by accident `ArgumentDefaultsHelpFormatter` `RawTextHelpFormatter`
A future PR should remove all instance `ArgumentDefaultsHelpFormatter` to uniformize our docstring.
@arnaudbore

**Comment by frheault** [comment]
@arnaudbore This can be closed
