### ISSUE TITLE
I don't really mind, but based on François's previous question about trying to have the same nomenclature everywhere:

### ISSUE THREAD

**Issue by arnaudbore** [scilus/scilpy#213]
I don't really mind, but based on François's previous question about trying to have the same nomenclature everywhere:

Everywhere else, it is called _mean_std, not _stats. I think I actually prefer stats but then maybe we should change it everywhere else?

_Originally posted by @EmmaRenauld in https://github.com/scilus/scilpy/pull/202_

**Comment by jchoude** [comment]
As said in the PR, stats covers more than mean ans std, normally

**Comment by frheault** [comment]
@arnaudbore So do we close, since _stats do cover more, it makes sense.
