### ISSUE TITLE
scil_visualize_seed --save option

### ISSUE THREAD

**Issue by mdesco** [scilus/scilpy#220]
@AntoineTheb is the behavior like we really want?
Right now, for example, I'm looping over 30 bundles and I scil_visualize_seed.py track.trk --save track.png to have the 30 PNG files.

But I need to close the VTK window 30 times. Is this wanted? Probably not?

Also, how hard to add the seed option to scil_visualize_bundle_mosaic?

Thanks!

**Comment by frheault** [comment]
Without adding an option it would be possible after PR #212 !
scil_visualize_bundle_mosaic.py will soon support nifti, so you could simply save the density map and then directly use them with the script.

**Comment by AntoineTheb** [comment]
I can easily add an option to not display the VTK window ! Also, I just looked at #212 (really cool !) and I could probably easily reuse some of the code to display everything in a mosaic instead of 30 separate images !

**Comment by arnaudbore** [comment]
#212 merged
