### ISSUE TITLE
scil_reorder_connectivity better help

### ISSUE THREAD

**Issue by mdesco** [scilus/scilpy#282]
1) --labels_list LABELS_LIST
                        List saved by the decomposition script,
                        the json must contain labels rather than coordinates.

Please say this is a txt file and add (.txt) at the end.

2) Also, not a fan of --prefix  why not just fix the output. Is it because the input can infact be *npy ? 

3) would be cool that input is *npy because if I start working on a sub-connectome of the full connectome, I want to reorder my vol.npy, len.npy, fa.npy, track-count.noy, etc... 

Thanks @frheault

**Comment by frheault** [comment]
@arnaudbore to close
