### ISSUE TITLE
scil_compute_connectivity allclose 'affine' too strict

### ISSUE THREAD

**Issue by mdesco** [scilus/scilpy#285]
This command breaks:
scil_compute_connectivity.py decompose_sub-1144_ses-2.h5 atlas/sub-1144_ses-2/brainnetome.nii.gz --volume volume.npy --streamline_count track-count.npy --length length.npy --metrics *fa.nii.gz fa.npy --density_weighting --no_self_connection -f

On this data:
https://www.dropbox.com/s/ursgtsbn26iakx1/conn.zip?dl=0

As recommanded by @frheault, if I comment the allclose 'affine' lines of the code, things run and seem to be fine.

**Comment by frheault** [comment]
@mdesco I cant see the data, but I made a fix. Can you test it (see latest PR)? Or send me back the data?

**Comment by mdesco** [comment]
Works all good now with P292
