### ISSUE TITLE
scil_recognize_multi_bundles.py: Invalid example

### ISSUE THREAD

**Issue by AntoineTheb** [scilus/scilpy#289]
The doc for `scil_recognize_multi_bundles.py` mentions

```
Example data and usage available at: https://zenodo.org/deposit/3613688
```

However, the link seems to be dead or something changed because when I try to access it, I get

![image](https://user-images.githubusercontent.com/10272382/88851774-45e5d080-d1bb-11ea-882b-031ad85c1453.png)

Is it supposed to be restricted ? Or did I miss that I must ask for access ?

**Comment by GuillaumeTh** [comment]
Fixed in PR #290
