### ISSUE TITLE
PFT script default params

### ISSUE THREAD

**Issue by StongeEtienne** [scilus/scilpy#319]
I think we should change the default PFT script params, to the original in Gabriel Girard Paper
step size of 0.2
and @gabknight might want to check for others in "scil_compute_pft.py"
https://github.com/scilus/scilpy/blob/master/scripts/scil_compute_pft.py

**Comment by mdesco** [comment]
I agree. I'm not fully comfortable with the 0.5 default. I know it is faster but with Compute Canada and our future ensemble tracking version, this should not be an issue for too long...
