### ISSUE TITLE
Trouble with scil_compute_bundle_profiles.py

### ISSUE THREAD

**Issue by Rad-dude** [scilus/scilpy#379]
Dear Scilpy developers,

First of all, thanks a lot for making the code openly available.

I am getting an error and failed execution of scil_compute_bundle_profiles.py with tck inputs.

Here's my command:
scil_compute_bundle_profiles.py $(pwd)/sub-PT_TCKs_output/PyT_all_LT_output/PyT_all_LT_filt3_BT.tck $(pwd)/fa_reg2T1w.nii --reference $(pwd)/fa_reg2T1w.nii --in_centroid $(pwd)/trial_centroid.tck

Here's the error message:
Traceback (most recent call last):
  File "/path_to/opt/anaconda3/bin/scil_compute_bundle_profiles.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/path_to/scilpy/scripts/scil_compute_bundle_profiles.py", line 131, in <module>
    main()
  File "/path_to/scilpy/scripts/scil_compute_bundle_profiles.py", line 74, in main
    assert_same_resolution(args.in_metrics + [args.in_bundle])
  File "/path_to/scilpy/scilpy/io/image.py", line 25, in assert_same_resolution
    if not is_header_compatible(images[0], curr_image):
  File "path_to/opt/anaconda3/lib/python3.8/site-packages/dipy/io/utils.py", line 323, in is_header_compatible
    affine_2, dimensions_2, voxel_sizes_2, voxel_order_2 = get_reference_info(
  File "path_to/opt/anaconda3/lib/python3.8/site-packages/dipy/io/utils.py", line 292, in get_reference_info
    raise TypeError('Input reference is not one of the supported format')
TypeError: Input reference is not one of the supported format

Scilpy is installed under anaconda3 on Mac OSX 10.13.6.
Other scil scripts are working fine, for example:
scil_compute_centroid.py --reference ./sub-PT_prep/sub-PT_T1brain_MSinFA_Warped.nii.gz ./sub-PT_TCKs_output/PyT_all_LT_output/PyT_all_LT_filt3_BT.tck ./trial_centroid.tck

This makes me think that the problem is not with the environment, nor with the reference image itself.

Any help would be appreciated.

Best,
Ahmed Radwan

**Comment by AntoineTheb** [comment]
Hi @Rad-dude, thanks for submitting this issue ! 

The error message may be misleading and from the stack-trace you provided, it seems that the problems stems from elsewhere: `scilpy.io.image.assert_same_resolution` tries to verify that the `.tck` passed as argument to `scil_compute_bundle_profiles.py` lives in the same space as the `.nii` provided. However, `dipy` does not handle `.tck`s alone and need them to be loaded as `StatefulTractogram`s beforehand. This is indeed an issue on our end.

I will make a fix for this ASAP and link it to this issue.

**Comment by Rad-dude** [comment]
Hi @AntoineTheb 

Thanks for the quick response.

Indeed, since posting the issue I tried making a python script as an alternative.
I used scil_compute_bundle_profiles.py for inspiration.

The following fails:
img, img_affine = load_nifti(reffile)
tck_in = load_tractogram(inputfile, img_affine).streamlines

This works fine though (tested on Mac OSX only so far):
refff = nib.load(reffile)
tck_in = load_tractogram(inputfile, refff).streamlines

**Comment by arnaudbore** [comment]
Dear @Rad-dude ,

Everything should be fixed now. It has been merged.  
You can give it a try.

**Comment by Rad-dude** [comment]
Thanks @arnaudbore, but after doing git pull and reinstalling, I can't find the script scil_compute_bundle_profiles.py on my path anymore, checking the scripts folder also showed that it's not included anymore.

Is this a mistake or has it been removed?

**Comment by arnaudbore** [comment]
It has been removed since it was redundant with `scil_compute_bundle_mean_std_per_point.py`. 
Combined with `scil_compute_centroid.py` and `scil_compute_bundle_voxel_label_map.py` tractometry becomes more robust than the previous script.

**Comment by Rad-dude** [comment]
@arnaudbore okay, thanks. 

Just to clarify, the tractometry workflow is now:

1- scil_compute_centroid.py to get centroid which is needed for next step.
2- scil_compute_bundle_voxel_label_map.py to get the nifti map of the subsegmented bundle using NN on the points of the bundle centroid (optional args. --out_labels and --out_distances at least should be used)
3- scil_compute_bundle_mean_std_per_point.py 
(this one points to scil_label_and_distance_maps.py in the help text, but this command seems to have been deprecated)

If it's not too much trouble, I have a few more questions:
1- Are the distance maps the same as the output of dipy.stats.analysis.gaussian_weights?

2- Do I need to orient the streamlines even if i'm not using a template bundle? 
(I thought it was not necessary but wouldn't do any harm if included, bundles look the same if saved)

3- Is there a scilpy function to plot the output .json? 

Below is a snippet of what I was doing when scil_compute_profiles.py failed initially.

import dipy.stats.analysis as dsa
import dipy.tracking.streamline as dts
from dipy.segment.clustering import QuickBundles
tck_in = load_tractogram(inputfile, refff).streamlines

            # QB stuff
            feature = ResampleFeature(nb_points=100)
            metric = AveragePointwiseEuclideanMetric(feature)
            qb = QuickBundles(np.inf, metric=metric)
            clust_tck = qb.cluster(tck_in)
            # find your center
            tck_cent = clust_tck.centroids[0]
            # extra measure.. orient by self!
            reor_tck = dts.orient_by_streamline(tck_in,tck_cent)
            # get your weights
            w_tcks = dsa.gaussian_weights(reor_tck)
            # calc profile using the weights
            fa_prof_tck = dsa.afq_profile(fa, reor_tck, fa_affine, weights=w_tcks)
            adc_prof_tck = dsa.afq_profile(adc, reor_tck, adc_affine, weights=w_tcks)

Thanks in advance.
