### ISSUE TITLE
Trouble with scil_visualize_bundles_mosaic.py

### ISSUE THREAD

**Issue by Rad-dude** [scilus/scilpy#386]
Greetings,

I was trying to use this function as follows:
scil_visualize_bundles_mosaic.py ./sub-x_prep/fa.nii.gz ./AF_all_LT_fin_WB_iFOD2.tck ./trial.png

But I keep getting this error, might this be related to the Statefultractogram issue again?

Traceback (most recent call last):
  File "/home/rad/anaconda3/bin/scil_visualize_bundles_mosaic.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/NI_apps/scilpy/scripts/scil_visualize_bundles_mosaic.py", line 355, in <module>
    main()
  File "/NI_apps/scilpy/scripts/scil_visualize_bundles_mosaic.py", line 166, in main
    tractogram = load_tractogram_with_reference(parser, args, filename)
  File "/NI_apps/scilpy/scilpy/io/streamlines.py", line 104, in load_tractogram_with_reference
    elif args.reference is None:
AttributeError: 'Namespace' object has no attribute 'reference'

Any input would be appreciated.

Thanks in advance.

**Comment by arnaudbore** [comment]
Thank you @Rad-dude for reporting this issue.

Did you try with the latest scilpy ?

We will quickly come up with a better error message here but if you use a tck file you need to add a reference.
Please add `--reference fa.nii.gz` to your command line.

**Comment by Rad-dude** [comment]
Hi @arnaudbore,

Thanks for the quick response.

I made sure to do a git pull and pip install before trying. 
This was also to try with scil_compute_bundle_profiles.py (which for some reason I cannot find anymore in the scripts folder).

I've just tried it with --reference as you suggested, but it didn't work, as --reference is an unrecognized option here.

Thanks in advance

**Comment by AntoineTheb** [comment]
Hi @Rad-dude.

`scil_visualize_bundles_mosaic.py` should work now ! Let us know if it's not

**Comment by Rad-dude** [comment]
Just tried, works now thanks a lot.

Output is not correctly oriented, even when pre-transformed to MNI, see attachment.

Not sure why, but I noticed it also happens with scil_screenshot_bundle.py as well.
Might it by my image affine?

![trial_1](https://user-images.githubusercontent.com/20127224/106488234-ca3f4600-64b3-11eb-8b6a-1abd85532301.png)

Thanks again.

**Comment by AntoineTheb** [comment]
Indeed, it seems the orientation is wrong. @frheault What do you think ? @arnaudbore Can you reopen the issue ?

**Comment by CHrlS98** [comment]
@AntoineTheb,
I think the `window.snapshot` method in FURY inverts the image for some reason. We call it here:
https://github.com/scilus/scilpy/blob/42e013209e9cb06df6848ee49b7792a916f54f75/scripts/scil_visualize_bundles_mosaic.py#L140
A workaround would be to use `fury.io.save_image` with the output from `window.snapshot`, reversed along an axis (I think it would be the first axis).

**Comment by AntoineTheb** [comment]
@CHrlS98 Good idea, but it feels hackish. However, looking at `window.snapshot`
https://github.com/fury-gl/fury/blob/9dd52233c07dd9f6bba2a164d26c48c4bcb0f23c/fury/window.py#L919
It seems the actual image is returned as a numpy array. If the return was used, it could be flipped and used consequently. I'll open a draft PR and investigate a fix

**Comment by CHrlS98** [comment]
@AntoineTheb Yeah,
Something like:
```
out_img = window.snapshot(...)
# Saving with window.shapshot inverts the image
# Using io.save_image fixes the issue
io.save_image(out_img[::-1], path)
```
has proven effective in the past in some other script I wrote in the past, and it might just work here!
