### ISSUE TITLE
png saved is flipped

### ISSUE THREAD

**Issue by arnaudbore** [scilus/scilpy#389]
scil_visualised_fodf gives a flipped png.

Maybe everything that will use `scilpy/viz/scene_utils.py`  -> `render_scene`  function

**Comment by arnaudbore** [comment]
@AntoineTheb can you fix this issue within your #388  ?

**Comment by AntoineTheb** [comment]
Sorry for the delay, on it !

**Comment by arnaudbore** [comment]
Fixed Thank you @AntoineTheb
