### ISSUE TITLE
scil_compute_todi.py defaults 

### ISSUE THREAD

**Issue by mdesco** [scilus/scilpy#408]
Can we please add the defaults in the -help. I do not see what the important defaults are by doing -h. This is annoying and I must go to the code.
--sphere
--sh_order
--sh_normed
--smooth

Also, not 100% sure what is the "length" weighted thingy... Should the non-length weighted be outputed too?

@StongeEtienne or @frheault  thanks

**Comment by StongeEtienne** [comment]
@mdesco I'm working on it,
added the "sphere" and "sh_order" default, however "smooth" and "sh_normed" are boolean.
I can rename the "sh_normed" to "normalize_per_voxel", to be simplier.

However for "smooth" it apply a spatial blur (gaussian sigma), and a directionnal blur (dot order).
do you want me to split it into 2 separate input ?   spatial_sigma  & directionnal_smoothing_order  (0 default for no blurr).

**Comment by StongeEtienne** [comment]
@mdesco *also, the "length" is to support compress streamlines (with non-uniform segment) so it weight each segment by their length.

**Comment by mdesco** [comment]
Thanks for the precision. No need to split the boolean smooth option.

Is the length the length of the track or length within the voxel? Please clearly the text at the beginning of the script.

Also, please clarify the --out_lw_todi option. This is a spherical function output, with the fourth dimension as big as the number of points on the sphere. This is become crazy big output...
