### ISSUE TITLE
Merge `scil_screenshot_bundle` and `scil_visualize_bundle`

### ISSUE THREAD

**Issue by AntoineTheb** [scilus/scilpy#415]
Either merge them or wrap up logic so it can be reused by both scripts. I don't have the time right now for this, but I'll leave this issue here to remind myself to do it eventually.

**Comment by arnaudbore** [comment]
We kept them separated but with two distinct names: 
```
scil_visualize_bundles.py -> scil_viz_bundle.py
scil_screenshot_bundle.py -> scil_viz_bundle_screenshot_mni.py
```
