### ISSUE TITLE
numpy version requirement error

### ISSUE THREAD

**Issue by sstojanovski** [scilus/scilpy#452]
The numpy 1.18.* requirement seems to be potentially to blame for the numpy error I encounter when testing scil_normalize_connectivity.py
Setup scilpy via graham:

1) virtualenv --no-download ~/SCIL
2) cd SCIL/bin & git clone https://github.com/scilus/scilpy.git
3) source ~/SCIL/bin/activate
4) pip install Cython --no-index ##encountered error due to lack of Cython module when pip installing
5) pip install -e .
6) cd SCIL/bin/scilpy
7) python setup.py install

error: 'numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject'
source: https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp

Not sure if editing the requirements is going to cause later chaos here.

**Comment by sstojanovski** [comment]
This error seems to be specific to setup on Graham - local setup was not problematic
Unsure on how to get around this

**Comment by sstojanovski** [comment]
Seems like you've got some other incompatibility problems introduced. I can see that you changed Pillow, which is now incompatible. Got this error when pip installing Cython 0.29.23: ERROR: scilpy 1.1 has requirement Pillow==8.2.*, but you'll have pillow 8.1.2 which is incompatible.

**Comment by liuzhenqi77** [comment]
I tried installing on Cedar, it seems the recent pull request that updated Pillow to 8.2.* is causing a problem. The newer version of Pillow has not been compiled to wheel by compute canada, and we cannot compile by ourselves because of some missing dependency libs. We could maybe email compute canada to have them compile an official wheel.

**Comment by liuzhenqi77** [comment]
No I didn't contact them. I was using another Pillow version.
