### ISSUE TITLE
scil_run_commit.py not robust to streamlines out of bounding box

### ISSUE THREAD

**Issue by NotaCS** [scilus/scilpy#504]
I ran scil_run_commit.py, and it worked great until the result saving phase:
It crashed when trying to save the non-essential tractogram (line 292) because of a problem with the bounding box. Fortunately, the essential tractogram was saved successfully.

I think it would be better to allow for the saving of "bad" streamlines (with a warning maybe), rather than a crash at the very end of the process.

**Comment by GuillaumeTh** [comment]
@mdesco weird it was supposed to generate clean tractograms. But yes we could add remove invalid streamlines in the PFT and Local tracking process in TractoFlow
