### ISSUE TITLE
scil_apply_transform_to_tractogram.py and pickled data

### ISSUE THREAD

**Issue by 5Elise** [scilus/scilpy#516]
Hi, I'm trying to transform my tractogram (generated with Tractoflow) into MNI space using scil_apply_transform_to_tractogram.py but I get this error message, should I add allow_pickle=True ? if yes where exactly?

File "/myenv/lib/python3.8/site-packages/numpy/lib/npyio.py", line 445, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False

**Comment by arnaudbore** [comment]
This will remain unanswered. If needed and with proper data we can reopen the issue and then fix it.
