### ISSUE TITLE
remove multiple_shell_energy.py redundancy with dipy code

### ISSUE THREAD

**Issue by arnaudbore** [scilus/scilpy#52]
Once https://github.com/nipy/dipy/pull/1711/files is merged in Dipy, we should use Dipy's version to have less code redundancy.

_Originally posted by @jchoude in https://github.com/scilus/scilpy/pull/32_

**Comment by frheault** [comment]
@arnaudbore Was this done ?

**Comment by arnaudbore** [comment]
Nope, I was really not feeling confident with this... Who wants to take care of it?

**Comment by arnaudbore** [comment]
After a short discussion with @frheault we are closing this issue since there is no easy plug with the dipy code and it's not really an issue or a big overlap of code.
