### ISSUE TITLE
assert_outputs_exist might be wrong

### ISSUE THREAD

**Issue by EmmaRenauld** [scilus/scilpy#521]
When checking if a directory exists with assert_outputs_exist: if the directory is listed as 'path/my_dir' or 'path/my_dir/' (with or without the trailing '/'), the result is not the same. At line `path_dir = os.path.dirname(path)`, in the first case, you will analyse 'path/' only.

**Comment by arnaudbore** [comment]
@EmmaRenauld if you want to check if a directory you need to use assert_output_dirs_exist_and_empty not assert_outputs_exist. Can I close this issue ?
