### ISSUE TITLE
New tracking script needs verification for mmap

### ISSUE THREAD

**Issue by EmmaRenauld** [scilus/scilpy#531]
When all tracking PRs will be done, one thing will be left to re-code: see the #todos and the parameter --set_mmap_to_None.

@GuillaumeTh @CHrlS98 

Guillaume's analysis: Setting to None brings the data to RAM. Setting to 'r+' keeps it on disk. Back then, RAM was not good enough, but by now, we have improved the seed generation (on the fly) and improved our computers, using None should be fine. Charles should test and comment soon.

**Comment by arnaudbore** [comment]
Is it still an issue ? @EmmaRenauld @CHrlS98  ?
