### ISSUE TITLE
Minor inconsistency in scil_visualize_bingham_fit.py

### ISSUE THREAD

**Issue by mdesco** [scilus/scilpy#533]
Help says "Visualize 2-dimensional Bingham volume slice loaded from disk. The volume is
assumed to be saved from scil_compute_bingham_fodf_metrics.py." but I think it should now say from scil_fit_bingham_to_fodf.py

**Comment by CHrlS98** [comment]
Indeed, I'll add to PR #527 !

**Comment by arnaudbore** [comment]
@CHrlS98 do you confirm this has been fixed in #527 ?

**Comment by CHrlS98** [comment]
Yes I confirm, this issue can be closed! It has been fixed.
