### ISSUE TITLE
Bug in scil_apply_bias_field_on_dwi

### ISSUE THREAD

**Issue by nilgoyette** [scilus/scilpy#546]
Hello there. I found a bug in `scil_apply_bias_field_on_dwi` while debugging my own version.

    chunk = np.arange(0, len(in_data), 100000)
    chunk = np.append(chunk, len(in_data) - 1)   # WHY -1 HERE?
    for i in range(len(chunk)-1):
        nz_bc_data = bc_data[chunk[i]:chunk[i+1]]
        rescale_func = np.vectorize(_rescale_intensity, otypes=[np.float32])

I believe that the `-1` is removing one voxel from the jobs list. Can you please check this and confirm that there's a problem?

**Comment by frheault** [comment]
I confirm this is not the intended behavior, it seems like a single voxel is left out at the end. I can do a PR to fix this, I doubt this had major consequences.

Good catch!

**Comment by GuillaumeTh** [comment]
Not fixed yet.
