### ISSUE TITLE
Deletes files with no warning

### ISSUE THREAD

**Issue by EmmaRenauld** [scilus/scilpy#55]
If there are files in --output_dir of scil_recognize_multi_bundles, they are deleted with no warnings!

**Comment by arnaudbore** [comment]
Did you use the option `-f (Force overwriting of the output files.)` ?

**Comment by EmmaRenauld** [comment]
Yes, but it deleted everything, even unrelated stuff.

**Comment by GuillaumeTh** [comment]
That's normal. The script delete all the outputs (even output_dir). So if you create manually something in the output dir, it will be deleted.

**Comment by EmmaRenauld** [comment]
Isn't it dangerous. I made a mistake on my output_path when calling it. Got everything erased...

**Comment by jchoude** [comment]
It might be a bit dangerous, but on the other hand, it's quite hard to know in advance exactly what files will be created and check only those.
