### ISSUE TITLE
--binary not read by Mi-Brain

### ISSUE THREAD

**Issue by EmmaRenauld** [scilus/scilpy#579]
From what I've seen, outputs from scripts with option --binary are not perceived by Mi-Brain as binary in the way that they cannot be used with the segmentation tools (warning Segmentation is neither of type 'unsigned char' nor type 'unsigned short').

I wouldn't want to risk changing result for any user so I'm not sure whether we should modify all scripts offering the --binary option. @frheault  @arnaudbore 

ex: scil_compute_density_map,scil_compute_seed_density_map (both np.int32), scil_compute_endpoints maps (I just added this binary option in PR 571, but I copied from density_map) ,

**Comment by frheault** [comment]
@arnaudbore #685
