### ISSUE TITLE
Reorg of tractogram filtering functions

### ISSUE THREAD

**Issue by grahamlittlephd** [scilus/scilpy#605]
Hey all,

I was just messing around with tractogram filtering using 3D meshes and ran into an issue when I was deciding what module I should put my function in.

There are a ton of places in scilpy with filtering functions in scilpy.
tracking/tools.py - has a bunch of filtering based on length
segment/streamlines.py - has a bunch of filtering based on ROIs
utils/streamlines.py - has a filter operation based on streamline IDs

Should we consolidate these functions into their own filter module or something similar. This would help prevent things from diverging too far and we end up replicating code.  I'm happy to do this as long as we can get some agreement on a plan.

**Comment by mdesco** [comment]
@arnaudbore @grahamlittlephd  can we bring this up next lab meeting and discuss all together?
If you cannot wait a week, I suggest you guys meet with the other scilpy developers to discuss this. Maybe a good idea to invite @frheault

**Comment by grahamlittlephd** [comment]
This can wait a week, no problem.  We can discuss at the next meeting

**Comment by arnaudbore** [comment]
@EmmaRenauld does this include the work you've been doing with the last PRs ?

**Comment by EmmaRenauld** [comment]
Yes, most of it, and we're not done. You're welcome in a next "scilpy reorganization" meeting, Graham.

**Comment by arnaudbore** [comment]
WIP no need for an issue. See with @EmmaRenauld
