### ISSUE TITLE
Doubled code

### ISSUE THREAD

**Issue by EmmaRenauld** [scilus/scilpy#620]
Some code for the scil_score_tractogram and scil_evaluate_bundle_pairwise_agreement (intended use: reproducibility studies) are very similar (ex: Dice score / f1 score is computed in both) and this should be cleaned eventually.

@AntoineTheb

**Comment by arnaudbore** [comment]
I think we can close this issue @EmmaRenauld  ?

**Comment by arnaudbore** [comment]
WIP see @EmmaRenauld if needed.
