### ISSUE TITLE
Mask interpolation in tracking scripts

### ISSUE THREAD

**Issue by CHrlS98** [scilus/scilpy#624]
In `scil_compute_local_tracking.py`, mask interpolation is nearest-neighbor while in `scil_compute_local_tracking_dev.py` it defaults to trilinear.

Should we uniformize this? @EmmaRenauld @arnaudbore

**Comment by EmmaRenauld** [comment]
I'm not opposed at all. I just used defaults from the old bitbucket.

**Comment by CHrlS98** [comment]
I'll write a pr to change the default in dev script.
