### ISSUE TITLE
scilpy is broken on Python3.10

### ISSUE THREAD

**Issue by guruevi** [scilus/scilpy#680]
Due to dependencies on old numpy/scipy which have bugs when compiling on newer Python. Some of these bugs are fixed in later versions of NumPy

Due to my personal lack of knowledge on this package, I'm not sure if updating the requirements.txt would break something in scilpy (since they are locked to a particular sub-version, my intuition tells me there must be a reason)

Downgrading to Python3.7 (according to this git repo, it is what you use for testing) I still get errors compiling the desired version of NumPy on a modern version of Ubuntu (22).

**Comment by arnaudbore** [comment]
Hi @guruevi ,

We have a current PR #678  that is meant to fix all these issues and make scilpy compatible with python 3.10.
You can give a try and give your feedback about this PR. 
Our plan is to make sure all scilus flows and scilpy are python 3.10 compatible by the end of March.

Best,
Arnaud

**Comment by guruevi** [comment]
Thanks, that seems to have worked, I did need to install setuptools>=58.2.0 manually as the version that shipped in Ubuntu seems to be outdated.

So my commands (for people finding this issue):
pip install setuptools\>=58.2.0
pip install git+https://github.com/scilus/scilpy.git@dev

Thank you for the tip!
