### ISSUE TITLE
Investigating Dipy tracking??

### ISSUE THREAD

**Issue by EmmaRenauld** [scilus/scilpy#698]
Hi.

Here is an image of the Fornix obtained with `scil_compute_local_tractogram` vs `_dev`, with exactly the same parameters, then segmented the Fornix.

Up row: dev. Det = 39 streamlines , Prob = 85 streamlines.
Bottom: dipy. Det = 6 streamllines. Prob = 29 streamlines.

For both Det and Prob, our _dev tracking seems to be filling the space better. Are we sure that interpolation of the mask is managed correctly in Dipy? Should we investigate? My result could be due to random, but if we have time to verify...

![image](https://user-images.githubusercontent.com/4967417/227569709-0216ad18-f8fa-4122-87a2-24529aedd572.png)

**Comment by arnaudbore** [comment]
We should give it a try with the latest version and see if Gab's fix made a difference.

**Comment by EmmaRenauld** [comment]
I didn't finish running the scilpy_tracking_local_det (sooo soooo slow!)

But comparing dipy's proba vs our dev_prob: Issue seems ok.
![dipy_prob](https://github.com/scilus/scilpy/assets/4967417/5fd0bfc8-8b08-42fe-baef-a23cf3dc6bfe)
![dev_prob](https://github.com/scilus/scilpy/assets/4967417/699be239-7845-471e-ad2d-2fdea1379959)

**Comment by EmmaRenauld** [comment]
For comparison: dipy det. If one day I get the dev det, I'll show it here.
![dipy_det](https://github.com/scilus/scilpy/assets/4967417/09ae799b-1a6e-4cb4-ba7e-d66a00895bf9)
