### ISSUE TITLE
Error installing spams package from the scilpy requirements

### ISSUE THREAD

**Issue by jayashree15** [scilus/scilpy#741]
Hello, 

I'm trying to install the 1.5.0 version of scilpy as a part of KUL_FWT pipeline (https://github.com/KUL-Radneuron/KUL_FWT). I'm having issues installing in a virtual mamba environment (python=3.10) because the spams package (attached is the error text). I'm installing on a CentOS v7 system. Please let me know if you have any solutions.

Thanks!
[error_installing_spams.txt](https://github.com/scilus/scilpy/files/12476101/error_installing_spams.txt)

Jayashree

**Comment by AlexVCaron** [comment]
Hello Jayashree,

You seem to be missing Lapack in your environment. You can install it through mamba. Please check if Blas is also installed. Those two dependencies are required to build Spams.

**Comment by jayashree15** [comment]
Thank you, that helped!

Jayashree

**Comment by jayashree15** [comment]
Resolved
