### ISSUE TITLE
Missing documentation for scilpy.tractanalysis.grid_intersections

### ISSUE THREAD

**Issue by CHrlS98** [scilus/scilpy#745]
Seems like a pretty powerful and useful function to compute the points at which a streamline intersects the voxel grid. However, there is no docstring and the actual expected input and behaviour are not clear at all.

From what I understood, expected input is in voxel space with corner origin, and returns the original streamlines containing an additional point for each voxel border the streamline crosses. Still, I'm not sure.

Anyone? @frheault @arnaudbore

**Comment by frheault** [comment]
I imagine @jchoude made that function. Maybe he remembers?
