### ISSUE TITLE
Manage test data aside of git commits

### ISSUE THREAD

**Issue by AlexVCaron** [scilus/scilpy#794]
Test data is badly scoped, e.g. we have one big repo that when updated works for a single PR, but make every other errors out, since we don't have any versioning capabilities.

What we want :
- When a PR is submitted : scope test data to the PR. The PR can change the data, but those changes cannot affect other PR or any other testing infra (local testing, branch testing, master testing).
- On the master branch : run all tests with all up-to-date test data. Data need to be robustly versioned to do this, once bound to a master commit, the data package must NEVER change.
- On a specific branch : scope test data to the branch. To do this, we need to keep versioning of all test datasets bound to branch. If we can go further, we should bind to every commit. this can be easily done if we have the space. The latter has to grow sub-linearly with the number of commits (if we submit all test data to versioning, it could easily go exponential, which is not good, we'll explode the disk space).
- On a specific branch on a fork : same as for the branch, but test data storage cannot be handled by us, it need to be scoped to the user's resources.

Solutions to do the work :
- Storage backends : google drive could still works, aws storage, azure cloud, git, any other solution
- Versioning strategies :
  - Git LFS :
      - Integrates directly with git
      - No versioning, data will change with commits
      - From this, perfect scoping to commit, data will follow repository structure seamlessly
      - However, need to store all those images in the repository, could end up lacking space
  - DVC : from the acronym, Data Version Control.
      - Developed to save ML models through iterations
      - Super robust
      - Sidelines with git (you commit your files to a backend, a local DB gets updated and commited to git)
      - has a google drive backend (allow incremental standardization)
  - This is the extent of my research for now, please submit other solutions you consider would be good !

Right now DVC seems to be the workhorse for our use-case:
- It is simple, yet covers most of all the cases we need when testing.
- Correctly configured, it should work as good as git LFS in terms of scoping.
- The upside is that data is not stored in the repository but on a backend of choice.
- The fetcher's code must be updated to scope correctly, but its implementation is well isolated so it should not be hard
- This is a new convention to take on by the lab. If it is clear enough, it is a very good one to enforce though.

TODO : 

- [ ] Investigate if there is other versioning solutions that are interesting.
- [ ] Investigate which backend would be the most interesting to host test data.
- [ ] Check if DVC can easily scope test data across forks, so we don't host forks deltas (but at the same time, the whole procedure still works for them)

**Comment by arnaudbore** [comment]
DVC is online :+1:
