### ISSUE TITLE
MSMT_frf and fODF inconsistency with --tolerance on b-values

### ISSUE THREAD

**Issue by mdesco** [scilus/scilpy#830]
If you compute a multishell FRF with a certain tolerance to, for example merge b=350 and b=400 into the same shell, and have only one FRF for that shell, you then, cannot apply this FRF in the compute_fodf script because there is no --tolerance there.

scil_compute_msmt_frf.py ../../sub-001_dwi.nii.gz ../../sub-001_dwi.bval ../../sub-001_dwi.bvec --mask b0_mask_mask.nii.gz frf_wm.txt frf_gm.txt frf_csf.txt --tolerance 105 -f -v

scil_compute_msmt_fodf.py ../../sub-001_dwi.nii.gz ../../sub-001_dwi.bval ../../sub-001_dwi.bvec --mask b0_mask_mask.nii.gz frf_wm.txt frf_gm.txt frf_csf.txt --processes 6

The second command will then break.... 

@karanphil can you fix please. 

Data available here: https://www.dropbox.com/scl/fi/1iiauu9li3ulkk6tqxkba/multishell.zip?rlkey=vb1mg38kjxgxo0j30iqn7meyk&dl=0

**Comment by karanphil** [comment]
Hi Max, there is in fact a `--tolerance` option in `scil_fodf_memsmt.py`. It should work the same as in `scil_frf_memsmt.py`. Can you try with it?
