### ISSUE TITLE
Warning for descoteaux basis

### ISSUE THREAD

**Issue by EmmaRenauld** [scilus/scilpy#865]
When running scil_dwi_to_sh:

PendingDeprecationWarning: The legacy descoteaux07 SH basis uses absolute values for negative harmonic degrees. It is outdated and will be deprecated in a future DIPY release. Consider using the new descoteaux07 basis by setting the `legacy` parameter to `False`.

**Comment by CHrlS98** [comment]
I changed the definitions of SH bases in DIPY back in 2020 to agree with the versions described in the cited papers. There is most likely also a warning for the Tournier basis. I think first a first step would be to update the `add_sh_basis_arg` method to support legacy and non-legacy bases.

**Comment by arnaudbore** [comment]
#921
