### ISSUE TITLE
Default logging level

### ISSUE THREAD

**Issue by EmmaRenauld** [scilus/scilpy#879]
Now that we print the scilpy version, something like:

```
for bundle in *
do 
      echo $bundle
      scil_tractogram_convert.py $bundle bundle.trk
done
```

Will output:
```
BPS_left
INFO:root:Scilpy version: 1.7.dev0
BPS_right
INFO:root:Scilpy version: 1.7.dev0
CA
INFO:root:Scilpy version: 1.7.dev0
CC
INFO:root:Scilpy version: 1.7.dev0
Cingulum_left
INFO:root:Scilpy version: 1.7.dev0
Cingulum_right
INFO:root:Scilpy version: 1.7.dev0
CP
INFO:root:Scilpy version: 1.7.dev0
Fornix
INFO:root:Scilpy version: 1.7.dev0
ICP_left
[...]
```

Which is a little ugly. We should make sure that the version only shows with option -v.

**Comment by EmmaRenauld** [comment]
@frheault You were looking for easy tasks.

**Comment by arnaudbore** [comment]
I think it may be more complicated and heavy than anticipated. There is not consensus across scripts on how verbose is used.  Adding this in each script implies to duplicate code or to add a function to properly set verbose on each script. :thinking:

**Comment by EmmaRenauld** [comment]
Maybe the version could be added as epilog in all argparsers? So it would only print with --help?
(We would need to see what to do when there's already an epilog...)

**Comment by karanphil** [comment]
Also, a default logging.INFO might be to much verbose... what about logging.WARNING as default? And if you put -v, you then get logging.INFO or DEBUG. I could do a PR for this, looking at every scripts.

**Comment by EmmaRenauld** [comment]
Rapidly, I feel like it's a good option but maybe I don't have all scripts in mind.
