### ISSUE TITLE
BUG: `scil_tractogram_commit.py` crashes without a mask

### ISSUE THREAD

**Issue by AntoineTheb** [scilus/scilpy#932]
`scil_tractogram_commit.py` crashes if the argument `--in_tracking_mask` is not passed:

![Screenshot from 2024-03-04 16-59-14](https://github.com/scilus/scilpy/assets/10272382/2a8dd7c8-422c-4b9a-895f-073916688ae0)

The uninitialized variable is named 'niiMASK', which could be an indicator to the source of the problem. The stack trace points to code inside of commit, not scilpy, so the issue might be with commit itself.

**Comment by arnaudbore** [comment]
works like a charm with newest version of dmri-commit I will suggest a PR.

**Comment by AntoineTheb** [comment]
Solved in #934
