### ISSUE TITLE
NLmeans unclear!

### ISSUE THREAD

**Issue by EmmaRenauld** [scilus/scilpy#939]
Hey!

The mandatory argument `number_coils` in scil_denoising_nlmeans.py is never used! 

- We verify if it is >0 to decide between Rician and Gaussian. But you can put 1, 2, 4, it does change anything!
- The call to dipy's estimate_sigma uses N=0, where N is the number of coils, so we always enforce 0. https://github.com/scilus/scilpy/blob/master/scripts/scil_denoising_nlmeans.py#L63

Who can help me decide what to do.

Other questions: 
- we take the median of the std, but it is not explained why not the mean.
- All the comments in that script seem old and deprecated.  There has been no change to this script since Neil Goyette's work in 2017 (see bitbucket: https://bitbucket.org/sciludes/scilpy/annotate/master/scripts/scil_run_nlmeans.py?at=master). Ex: It talks about bval but this script works on any data. Can I delete all the comments?

**Comment by mdesco** [comment]
@EmmaRenauld let me know when you have checked the bitbucket and made an attempt. Our latest team's discussion said we would try to have something like:
--gaussien: vous savez que c'est gaussien.
--ricien: vous savez que c'est ricien
 
--sigma: votre sigma
--piesno N. utiliser piesno pour tenter de découvrir. Vous devez connaître le nombre de coils.
 
--N: NB de coils
