### ISSUE TITLE
scil_tractogram_uniformize_endpoints.py : Can not use target_roi with an atlas and a label. 

### ISSUE THREAD

**Issue by matthieudumont** [scilus/scilpy#962]
_assert_inputs_exist_ assumes all values of the _nargs_ should be files. 

When calling with:
`scil_tractogram_uniformize_endpoints.py AF_L.trk AF_L_uniformized.trk --target_roi 002_S_4213-a3_bl__aparc_aseg.nii.gz 1027`

I get:
`scil_tractogram_uniformize_endpoints.py: error: Input file 1027 does not exist`

**Comment by arnaudbore** [comment]
Good call @matthieudumont we will fix this asap.

**Comment by arnaudbore** [comment]
@matthieudumont this has been fixed.
